name: push to quay

on:
  push:
    branches: 
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
            registry: quay.io/sustainable_computing_io
            username: ${{ secrets.BOT_NAME }}
            password: ${{ secrets.BOT_TOKEN }}
      - name: Build and push multi-arch kepler image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./build/Dockerfile
          platforms: linux/amd64,linux/s390x,linux/arm64
          push: true
          tags: quay.io/sustainable_computing_io/kepler:latest
